### PR TITLE
Fix various naming inconsistencies

### PR DESCRIPTION
**Pull request by caruccio**
Inconsistent filename

## Description
Please include a summary of the change, the motivation, and any additional context that helps others understand your PR.

## Linked Issues
If these changes close one or more open issues, [please tag them as described here](https://help.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword).

## How has this been tested?
- Describe the tests that you ran to verify your changes.
- Provide instructions so we can reproduce.
- List any relevant details for your test configuration.

## Checklist
- [ ] I have labeled this PR with the relevant [Type labels](https://github.com/undistro/.github/labels?q=Type%3A)
- [ ] I have documented my code (if applicable)
- [ ] My changes are covered by tests

### CODE REVIEW

**Comment by lucasjct** [comment]
Hi @caruccio 
Thank you for your contribuition.

I saw that the test don't passed. We need to rename the file of test with the same name of file check.

For example:

File check: M-400_image_tagged_latest.yaml
File test: M-400_image_tagged_latest_test.yaml

You can see the this file test here:
https://github.com/undistro/marvin/tree/main/internal/builtins/general

**Comment by caruccio** [comment]
Hey @lucasjct. I've submitted more naming changes. Can you please review, and if it's fine squash and rebase?

**Comment by caruccio** [comment]
Forgot one file.

**Review by lucasjct — APPROVED** [review]
@caruccio , after run locally this branch and run the test and scan, we can assure everthing is ok. 
@matheusfm  fyi

**Pull request merged**
